# Generated by Django 6.0.1 on 2026-04-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_id', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('views', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
